### ISSUE TITLE
Release 1.0

### ISSUE THREAD

**Issue by dereuromark** [php-collective/decimal-object#1]
TODO

- [ ] Finish API - see wiki
- [x] Add typehints where feasible (and not counter-productive)

**Comment by dereuromark** [comment]
@vansari Do we want to add anything to the public api before tagging a release?

**Comment by vansari** [comment]
@dereuromark I think the work is done and we can create a first stable release. In the future we can walk through the code and change some lines where it is necessary or possible. 👍

**Comment by dereuromark** [comment]
Well, we cannot add bc breaking changes, that usually includes new methods etc.

**Comment by vansari** [comment]
Yes that's right. We can only tune up code which doesn't break anything 😉

So feel free to create the first stable release! 🎉

**Comment by dereuromark** [comment]
What about some of those changes of https://github.com/spryker/decimal-object/pull/21/files ?
Do you think they still make sense?
- Stringable

**Comment by vansari** [comment]
@dereuromark  thanks for the changes and sry for the delay.
I will add the other changes of the old Change Request to this new Repo in the next few days
