### ISSUE TITLE
Issue with stringable objects

### ISSUE THREAD

**Issue by DannyMeyer** [php-collective/decimal-object#11]
Stringable objects are being casted to late.

So when you have this setup:
```php
class foo implements Stringable {
    public function __toString(): string
    {
        return 'bar';
    }
}

$d = new Decimal(new foo, 5);
var_dump($d);
var_dump($d->toString());
```
It will be used successfully. Output of above:
```
class PhpCollective\DecimalObject\Decimal#3 (2) {
  public $value =>
  string(3) "bar"
  public $scale =>
  int(5)
}
```
```
string(3) "bar"
```

**Fix:** in `parseValue` cast stringable objects before the string check will be done.

**Comment by dereuromark** [comment]
What kind of class is this that doesnt work?
I am surprised as there are existing tests  ( $objectWithToStringMethod ), and they seem to work.

**Comment by dereuromark** [comment]
PR open.
